create table users(
    id int generated by default as identity primary key,
    email varchar(200) not null unique,
    name varchar(20) not null,
    age smallint check ( age > 0 and age < 150),
    password varchar(100) not null,
    role varchar(50) check ( role in ('ROLE_USER', 'ROLE_ADMIN') ) not null
);